### PR TITLE
Use relativepath for file inputs so that task inputs are relocatable

### LINKED ISSUE #314: pitest build cache not working if the absolute path changes
Steps to reproduce:

- Clone a project with pitest to a folder "A" and run pitest task
- Run pitest task again and the build cache kicks in and reports FROM-CACHE as expected
- Clone the same project to a folder "B" and run pitest task
- Since the absolute file paths have changed, pitest task is rerun run again with a different cache key

This causes CI builds to rerun pitest for every build when there are no code updates

Additional information:
Gradle version - 7.5

Attaching sample project to run the pitest task
[sample_building_java_applications-kotlin-dsl.zip](https://github.com/szpak/gradle-pitest-plugin/files/9251461/sample_building_java_applications-kotlin-dsl.zip)

Running from two different folders produces two different cache keys

```
Stored cache entry for task ':app:pitest' with cache key 4668219a852060cc33eb7756bcde035c
Stored cache entry for task ':app:pitest' with cache key 05465e68091575f0fe62c6e51188307c
```

From my cursory knowledge of gradle plugin development, I see no issues in the PitestTask.groovy file. All file properties are annotated with `@PathSensitive(PathSensitivity.RELATIVE)`

### PR DESCRIPTION
**Pull request by SidB3**
closes #314

### CODE REVIEW

**Comment by SidB3** [comment]
@szpak - A gentle reminder on the PR. Thanks!

**Comment by szpak** [comment]
Thanks. Relative paths here seem much more sensible. I'm not sure why the Travis checks didn't kick in :-/. I plan to merge it into devel to test it on CI and probably apply some other pending changes before releasing the new version.

**Comment by szpak** [comment]
It would be good to have some function test, but I'm not sure how TestKit deals with sharing the build cache (across tests and with the regular builds), so let's skip it.

**Comment by szpak** [comment]
Btw2, those inputs shouldn't be just `String`, however, in the times I started this plugin other fancy types were not available... I have to find out how much backward incompatible it would be to "enhance" them.

**Comment by SidB3** [comment]
Hi @szpak how's the testing going with this change? Any tentative timelines for putting out a new release?

**Comment by szpak** [comment]
@SidB3 There were some issues with the other changes in the plugin, but today I managed to merge it (manually) and released 1.9.0. Thanks for your contribution!

**Comment by SidB3** [comment]
Thank you!

**Pull request closed without merging**
