### PR TITLE
Ability to override `verbose` from command line

### LINKED ISSUE #349: Ability to override verbose from command line
Temporary enabling verbose output is very common to analyze issues when executing Pitest. 

Thus, it would be very useful to have a command line parameter for this like `./gradlew pitest --verbose`

There is already a documented way using the gradle-override-plugin, but adding additional plugins to a (complex) project is always challenging due to (in)compatibilities of Language Levels, Gradle-version, transitive dependencies etc. 

So for this "vital" option for temporary enabling verbose output it would be really helpful to have a "plugin-native" command line support.

### PR DESCRIPTION
**Pull request by Pfoerd**
When analyzing configuration failures of Pitest it's often necessary to temporarily turn on verbose output. Changing the configuration in gradle files is possible but obviously has some drawbacks.

This change adds the ability to turn on verbose output from the command line via an optional parameter:

`./gradlew pitest --verbose`

Fixes #349

### CODE REVIEW

**Comment by Pfoerd** [comment]
@szpak what do you think about this addition?

**Comment by Pfoerd** [comment]
Hi @szpak, any chance to get this released in the near future? We still have a great need for this :)

**Comment by szpak** [comment]
A good question. I don't remember, why I did merge it back them :thinking:

**Comment by szpak** [comment]
I've merged it into devel and it will be included in the next release. I have to do some housekeeping work before and in addition, due to the "recent" changes in Sonatype the releasing from CI might not work anymore. In the end in might take a moment to release.

As a workaround, you might define something like:
```groovy
pitest {
    verbose = project.findProperty("workaroundPitestVerbose") ?: "false"
```

in your build.gradle to be able to control it from the command line (probably you already have it defined that way ;-) ).

Thanks for your PR. Sorry for delay (I might missed it (?), as it looks good and same :thinking: ).

**Comment by Pfoerd** [comment]
No worries and thank you! You may also consider https://github.com/szpak/gradle-pitest-plugin/issues/350 for the next releases ;)

**Comment by Pfoerd** [comment]
Hi @szpak . Any chance to get this released soon?

**Pull request merged**
